// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpb0DA2NHTic6TBX03AvySuuxqU_XXg_g',
    appId: '1:444374881776:web:19df125c67be52adfcb935',
    messagingSenderId: '444374881776',
    projectId: 'waiting-time-app-74351',
    authDomain: 'waiting-time-app-74351.firebaseapp.com',
    storageBucket: 'waiting-time-app-74351.appspot.com',
    measurementId: 'G-2QJMEXMK2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkcuAdNAzeah_y2zpLJMxndQK7_SGAsgg',
    appId: '1:444374881776:android:90aab26eb3d6c036fcb935',
    messagingSenderId: '444374881776',
    projectId: 'waiting-time-app-74351',
    storageBucket: 'waiting-time-app-74351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi1dR1EQrHYcmlK4sTD9J3UK_bIYnmkIQ',
    appId: '1:444374881776:ios:deacf0d4764cc946fcb935',
    messagingSenderId: '444374881776',
    projectId: 'waiting-time-app-74351',
    storageBucket: 'waiting-time-app-74351.appspot.com',
    iosBundleId: 'com.example.waitingTime',
  );
}
